spring.datasource.url=${EPISODE_DB_URL:jdbc:mysql://localhost:3306/episode}
spring.datasource.username=${EPISODE_DB_USERNAME:episode}
spring.datasource.password=${EPISODE_DB_PASSWORD:episode}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
