spring.application.name=playback
server.port=8082

spring.datasource.url=${PLAYBACK_DB_URL:jdbc:h2:mem:playbackdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1}
spring.datasource.username=${PLAYBACK_DB_USERNAME:sa}
spring.datasource.password=${PLAYBACK_DB_PASSWORD:}
spring.datasource.driver-class-name=${PLAYBACK_DB_DRIVER:org.h2.Driver}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
