spring.datasource.url=${PLAYBACK_DB_URL:jdbc:mysql://localhost:3306/playback}
spring.datasource.username=${PLAYBACK_DB_USERNAME:playback}
spring.datasource.password=${PLAYBACK_DB_PASSWORD:playback}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
